### ISSUE TITLE
Parsing text based radeco-ir into graph representation

### ISSUE THREAD

**Issue by sushant94** [radare/radeco-lib#117]
This would allow us to write IR to files and load them up at a later point in the analysis. It would be nice if we could do this with a parser generator in rust, such as [lalrpop](https://github.com/nikomatsakis/lalrpop)

**Comment by HMPerson1** [comment]
I'd like to work on this.

So essentially I would write a function
```rust
fn parse_il(s: &str) -> SSAStorage
```
correct?

**Comment by sushant94** [comment]
@HMPerson1 Yes, that is the plan. I'd suggest making a simple version of it first, test it out. Then go top-down and add in missing information, enhance it, etc.
