### ISSUE TITLE
capstone rust build failed

### ISSUE THREAD

**Issue by Daniele-B** [radare/radeco-lib#124]
i've tried to install radeco from this github repository, but capstone_rust v0.2.3 failed to build.
this is the output i've got:

`Compiling capstone_rust v0.2.3 (https://github.com/sushant94/capstone-rust#6f780c04)
error: failed to run custom build command for 'capstone_rust v0.2.3 (https://github.com/sushant94/capstone-rust#6f780c04)'
process didn't exit successfully: '/root/radeco-lib/target/debug/build/capstone_rust-00189b7e7eda3d2b/build-script-build' (exit code: 101)
--- stdout
cargo:rustc-link-lib=capstone
src/wrapper.h:1:10: fatal error: 'capstone/capstone.h' file not found, err: true
--- stderr
src/wrapper.h:1:10: fatal error: 'capstone/capstone.h' file not found
thread 'main' panicked at 'Unable to generate bindings: ()', src/libcore/result.rs:906:4
note: Run with 'RUST_BACKTRACE=1' for a backtrace.`

I've tried install it on my kali linux machine.

**Comment by sushant94** [comment]
@Daniele-B Seems like you're missing capstone. Are you sure you have this installed on your system?

**Comment by MSleepyPanda** [comment]
FWIW, i've built radeco successfully on a fresh WSL (hence Ubuntu) installation by installing
- pkg-config
- clang
- libclang-dev
- libcapstone3
- libcapstone-dev
- libssl-dev
- radare2
- libradare2-dev

with apt from the default sources. Some things might be redundant (libclang-dev?) but it works for me.

**Comment by Daniele-B** [comment]
I didn't install libcapstone-dev, now capstone_rust compiles, but radeco lib says this:

` Compiling radeco-lib v0.1.0 (https://github.com/radare/radeco-lib#91845123)
error[E0554]: #![feature] may not be used on the stable release channel
  --> /root/.cargo/git/checkouts/radeco-lib-bf219eb1a7e916cc/9184512/src/lib.rs:46:1
   |
46 | #![feature(box_patterns)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
  --> /root/.cargo/git/checkouts/radeco-lib-bf219eb1a7e916cc/9184512/src/lib.rs:47:1
   |
47 | #![feature(box_syntax)]
   | ^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
  --> /root/.cargo/git/checkouts/radeco-lib-bf219eb1a7e916cc/9184512/src/lib.rs:48:1
   |
48 | #![feature(slice_patterns)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

error: Could not compile `radeco-lib`.

To learn more, run the command again with --verbose.`

**Comment by MSleepyPanda** [comment]
You need a nightly rust compiler. The preferred installation method for rust is [rustup](https://www.rustup.rs/).

You can either install the nightly toolchain as default when installing rustup or later on in the command line, given that rustup is in your PATH:
```
rustup install nightly
```
If you want to set nigthly as a default, execute
```
rustup default nightly
```
But if you want to use nightly only in this project, navigate to the root folder and execute
```
rustup override set nightly
```

If you want to update the stable or nightly version, execute
```
rustup update
```

If you want to pin the nightly to a specific version, replace `nightly` with `nightly-yyyy-mm-dd` in the commands above.

**Comment by sushant94** [comment]
This seems to be resolved. Closing.
