### ISSUE TITLE
parsing json fails on 'tachikoma'

### ISSUE THREAD

**Issue by crowell** [radare/radeco-lib#14]
```
[12:36:45] <mom> minishwoods tools/radeco ‹master*› » ./target/debug/cfg_ssa ../../dc23/ctf-services/services/defcon_finals_2015/tachikoma/tachikoma 
[12:36:45] <mom> Cannot find function at 0x0002b3f0
[12:36:45] <mom> thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(SyntaxError("EOF While parsing value", 1, 1))', ../src/libcore/result.rs:731
```

http://toonces.cat/tachikoma

**Comment by radare** [comment]
isnt this a bug in r2?

**Comment by radare** [comment]
also, that eof susggest me that the bug is in r2pipe.rs

**Comment by sushant94** [comment]
@radare @crowell , This has something to do with r2, not  with the pipe.
Though sym.main is identified, running `pdfj @ sym.main` says "Cannot find function at 0x0002b3f0"

**Comment by radare** [comment]
I would suggest handling “” as valid JSON from r2pipe.rs, this way commands like this, that doesnt display anything to stdout will not fail that hard, i think that we should handle better error cases like this from there. anyway, if there’s no function at sym.main is because the analysis hasnt been done properly, i see that you guys are doing “aa” for analysis, which is not the best way to get full analysis of the binary. what about af @ sym.main before running this? (just for testing)

**Comment by sushant94** [comment]
Yup. `af @ sym.main` followed by `pdfj @ sym.main` seems to work correctly.

**Comment by sushant94** [comment]
@radare Actually, the correct fix would be that r2 returns an empty array in these cases i.e. `"[]"`
This way, it'll still be a valid JSON.

**Comment by radare** [comment]
Thats not the same case. When the output is not json like an empty string it means that an error happened. We should handle this without a fatal exception. Maybe with Option or so

**Comment by sushant94** [comment]
@radare The idea thing would be to have the json be something like this:
```json
{
    "status": "ok",
    "contents": [
        { "foo": "bar" }, 
        {"apple": "mango"}
    ]
}
```

This way the error can be displayed to the user too.

**Comment by radare** [comment]
i think that we should assume that it is nearly impossible to handle all cases where the json is printed to extend that “status” field, because is a manual change. i would prefer to just handle non-json or empty output as error cases

**Comment by sushant94** [comment]
Fixed in radare/r2pipe.rs@a8831ddb99b2e61c941b4032987397e233ea717d

**Comment by radare** [comment]
😃
