### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by radare** [radare/radeco-lib#16]
I have removed the license commits for two reasons.

1) it was not discussed, accepted by at least me. Why BSD?

2) The commit was merged from the web user interface which poluted the commit history with two commits

**Comment by XVilka** [comment]
BSD was chosen because of the no limitations for using the code. What license you think of?

**Comment by radare** [comment]
Also, adding a license requires changing all source files and adding a header specifying that information.

**Comment by radare** [comment]
I was suggesting MIT, but there are also other licenses that can be interesting to use here. BSD seems a good license to me for this project because its suposed to be statically linked, and seems less restrictive/problematic than LGPL. Is @sushant94 and @dkreuter happy with it too? do you have other license proposals?

Licensing is serious thing, and have its legal implications, so better not to merge this kind of stuff without previous discussion. I guess that we all agree that we want:

* The author information to be kept along all possible forks/projects using it
* Allow anyone to use and modify this source without license restrictions

But i am a bit concerned about the "modify" part. Because, when i choosed LGPL for r2, this was because i wanted everyone to contribute into the main project, so if you have a privative project that uses r2 and you have to modify r2 core APIs or plugins to make it work with your tool, you MUST publish those changes, so everyone benefits.

This is not applicable to BSD, but as far as i know, there's no such license, maybe we can define a new license that takes the best of BSD and the best of LGPL.. some kind of LGPL2 with support for statically linking.. mainly because Rust doesn't allows dynamically linking crates. But as long as this is a compiler/language restriction.. this is somewhat anoying, because I guess this limitation will be dropped in future releases.

Enforcing anyone modifying its source to publish the changes benefits users and developers, while permitting 3rd party projects to use it. The main problem of GPL/LGPL is that people/companies are scared because of the viral nature of it and they use to be problematic when used in restrictive software.

**Comment by radare** [comment]
In short, I would choose LGPL if rust would support dynamically linking or LGPL was a bit less restrictive about statically linking. And maybe not having 'GPL' in the name would be less scary for companies.

**Comment by XVilka** [comment]
@radare we've discussed MIT (same as 2-clause BSD), but 3-clause BSD still saves the possibility to deny any relations to the project using radeco, if it is bad for the humanity, us or whatever.

**Comment by XVilka** [comment]
@radare but we can just remove 'modify' part from the BSD license and use it? Just change the name of the license..

**Comment by radare** [comment]
What i want is a mix of bsd and lgpl. And iirc theres no such thing. We can put our invented license. But if we do this we should push some efforts into clarifying all this. 

One of the goods of MIT is that its simple and easy, BSD Is too, but it have different versions and this makes it a bit more complex.

Licenses have been always an issue because legal stuff is hard and we developers dont want to care about this.

What do you think about my licensing ideas? Are you happy with it?

**Comment by sushant94** [comment]
But making our own license means that people have to actually make an effort to read this (which is usually not the case). If it is a standard license, then people are likely to just see the name and understand the terms of use along with it (which makes it easier for people).
I don't mind not compelling people to contribute back if they have modified the source for use within their projects, so for me BSD or MIT license seems ok/

**Comment by radare** [comment]
I think that bsd protects author names better than mit. So imho its good to choose bsd, and hopefully people will contribute back.. What about a dual license? I dont wanna make that too much complicated either

**Comment by radare** [comment]
meh, lets use BSD3. its fine for me

**Comment by XVilka** [comment]
:+1: 3-clause BSD

**Comment by radare** [comment]
Related https://en.wikipedia.org/wiki/BSD_licenses

**Comment by radare** [comment]
What about that last clause:
```
    * Neither the name of the <organization> nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.
```

freebsd license is simpler , it doesnt contains this one

**Comment by radare** [comment]
I also find this clause interesting:
```
3. All advertising materials mentioning features or use of this software
   must display the following acknowledgement:
   This product includes software developed by the <organization>.
```

**Comment by radare** [comment]
Done
