### ISSUE TITLE
Build Failing!

### ISSUE THREAD

**Issue by CoolOppo** [radare/radeco-lib#19]
[![Build Status](https://travis-ci.org/radare/radeco-lib.svg)](https://travis-ci.org/radare/radeco-lib)

I am getting the same errors as Travis-CI is when compiling. See https://travis-ci.org/radare/radeco-lib/jobs/80833855#L1329.

**Comment by radare** [comment]
The argparse branch is wip to fix this thing. Its a known issue as part of the refactoring to integrate with r2pipe.

**Comment by sushant94** [comment]
Fixed as of 64bd89b6b2f41e243f19a69a1e46899a60b93da0
