### ISSUE TITLE
unreachable code error

### ISSUE THREAD

**Issue by radare** [radare/radeco-lib#21]
It would be good to have some better feedback from the tool in order to understand the reason of this situation. i guess this is a bug in esil, but we dont know the address of that instruction or which function was trying to analyze, etc. (this happens with osx's /bin/ls) but probably with other binaries
```
$ target/debug/radeco /bin/ls
thread '<main>' panicked at 'internal error: entered unreachable code', /Users/pancake/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/frontend/esilssa.rs:100
```

**Comment by sushant94** [comment]
@radare Does this still happen? Have you tested this recently? I don't seem to be having this problem when I run it on OSX /bin/ls. Please confirm.

**Comment by VPaulV** [comment]
@sushant94 Yes, this still happens, but with other binaries.
[malware_sample.zip  - password: infected](https://github.com/radare/radeco-lib/files/271760/malware_sample.zip)

**Comment by sushant94** [comment]
@VPaulV Well ESIL recently underwent some changes that has made radeco pretty much un-usable. Give me a few days and it'll ~~all~~ mostly be fixed ;)

**Comment by sushant94** [comment]
This issue is no longer valid.
