### ISSUE TITLE
Move r2 module to r2pipe.rs

### ISSUE THREAD

**Issue by sushant94** [radare/radeco-lib#24]
The r2 module that implements some of the basic commands in order to make r2 easier to use from rust seems to be useful in repos other than radeco-lib too. I propose we move it to r2pipe, which will give user's an option to either use raw r2pipe or use r2 implementation that returns structs that are convenient to use.

**Comment by radare** [comment]
Ideally that should be done in another crate on top of r2pipe. I had the same  dilema when doing the other r2pipe apis. Because the idea would be to have some kind of common high level api on top of r2pipe for all languages, not just rust, for consistency

**Comment by sushant94** [comment]
Yes, that sounds like a nice goal. But imo, this can go into the same crate (in a different module) as it is essentially providing just convenience methods and the users can always just opt to not use these modules, but use raw r2pipes instead.
