### ISSUE TITLE
Building error: src/structs.rs:200:37: 200:38 error: mismatched types

### ISSUE THREAD

**Issue by XVilka** [radare/radeco-lib#25]
Compiling radeco-lib v0.1.0 (https://github.com/radare/radeco-lib#3becd4ac)
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:29:2: 29:63 warning: the trait `core::marker::Sized` is not 
implemented for the type `Self` [E0277]
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:29 	fn verify_block(&self, i: &Self::ActionRef) -> 
VResult<Self>;
                                                                                                   	
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:29:2: 29:63 help: run `rustc --explain E0277` to see a detailed 
explanation
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:29:2: 29:63 note: `Self` does not have a constant size known at 
compile-time
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:29:2: 29:63 note: this warning results from recent bug fixes and 
clarifications; it will become a HARD ERROR in the next release. See RFC 1214 for details.
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:29 	fn verify_block(&self, i: &Self::ActionRef) -> 
VResult<Self>;
                                                                                                   	
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:29:2: 29:63 note: required by `middle::ssa::error::SSAErr`
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:29:2: 29:63 warning: the trait `core::fmt::Debug` is not 
implemented for the type `Self` [E0277]
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:29 	fn verify_block(&self, i: &Self::ActionRef) -> 
VResult<Self>;
                                                                                                   	
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:29:2: 29:63 help: run `rustc --explain E0277` to see a detailed 
explanation
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:29:2: 29:63 note: `Self` cannot be formatted using `:?`; if it is 
defined in your crate, add `#[derive(Debug)]` or manually implement it
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:29:2: 29:63 note: this warning results from recent bug fixes and 
clarifications; it will become a HARD ERROR in the next release. See RFC 1214 for details.
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:29 	fn verify_block(&self, i: &Self::ActionRef) -> 
VResult<Self>;
                                                                                                   	
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:29:2: 29:63 note: required by `middle::ssa::error::SSAErr`
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:30:2: 30:61 warning: the trait `core::marker::Sized` is not 
implemented for the type `Self` [E0277]
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:30 	fn verify_expr(&self, i: &Self::ValueRef) -> 
VResult<Self>;
                                                                                                   	
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:30:2: 30:61 help: run `rustc --explain E0277` to see a detailed 
explanation
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:30:2: 30:61 note: `Self` does not have a constant size known at 
compile-time
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:30:2: 30:61 note: this warning results from recent bug fixes and 
clarifications; it will become a HARD ERROR in the next release. See RFC 1214 for details.
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:30 	fn verify_expr(&self, i: &Self::ValueRef) -> 
VResult<Self>;
                                                                                                   	
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:30:2: 30:61 note: required by `middle::ssa::error::SSAErr`
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:30:2: 30:61 warning: the trait `core::fmt::Debug` is not 
implemented for the type `Self` [E0277]
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:30 	fn verify_expr(&self, i: &Self::ValueRef) -> 
VResult<Self>;
                                                                                                   	
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:30:2: 30:61 help: run `rustc --explain E0277` to see a detailed 
explanation
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:30:2: 30:61 note: `Self` cannot be formatted using `:?`; if it is 
defined in your crate, add `#[derive(Debug)]` or manually implement it
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:30:2: 30:61 note: this warning results from recent bug fixes and 
clarifications; it will become a HARD ERROR in the next release. See RFC 1214 for details.
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:30 	fn verify_expr(&self, i: &Self::ValueRef) -> 
VResult<Self>;
                                                                                                   	
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xvilka/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/middle/ssa/verifier.rs:30:2: 30:61 note: required by `middle::ssa::error::SSAErr`
   Compiling radeco v0.1.0 (file:///home/xvilka/radare/radeco)
src/args.rs:213:22: 213:50 warning: unnecessary parentheses around `for` head expression, #[warn(unused_parens)] on by default
src/args.rs:213             for i in (0..(pipe.len() - 1) as u16) {
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/structs.rs:200:37: 200:38 error: mismatched types:
 expected `core::option::Option<radeco_lib::frontend::structs::LRegInfo>`,
    found `core::option::Option<r2pipe::structs::LRegInfo>`
(expected struct `radeco_lib::frontend::structs::LRegInfo`,
    found struct `r2pipe::structs::LRegInfo`) [E0308]
src/structs.rs:200             runner.state.reg_info = r;
                                                       ^
src/structs.rs:200:37: 200:38 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
Could not compile `radeco`.

**Comment by sushant94** [comment]
Seems like the r2pipe used is old. Running `cargo update` before build should solve this issue.
