### ISSUE TITLE
[CI] Fix Coveralls report

### ISSUE THREAD

**Issue by sushant94** [radare/radeco-lib#28]
The current coveralls report shown is incorrect as it includes r2's source as a part radeco (hence resulting in low coverage of 7%). 

/cc @XVilka @Maijin @radare

**Comment by radare** [comment]
how to reproduce this crash? isnt this an issue with kcov?

if anyone can get a backtrace… maybe we can tell travis to build r2 with asan, so we will get a crashlog when running with kcov.. but im not sure if kcov will work with asan

**Comment by sushant94** [comment]
@radare I'm not talking about the segfault when running with kcov. The problem is, kcov is considering r2 source (which is pulled and built) before running the tests, as a part of radeco's source code. Hence this results in it reporting a very low test coverage of 7% (which is certainly wrong).

**Comment by sushant94** [comment]
Fixed
