### ISSUE TITLE
Replace instruction pointer with address when used as operand

### ISSUE THREAD

**Issue by sushant94** [radare/radeco-lib#37]

**Comment by radare** [comment]
Maybe using r2.cmd("fd {addr}") to resolve address names?

**Comment by shakram02** [comment]
any info about this ? where to start ? example output ?

**Comment by kriw** [comment]
Is the goal of the issue fixing `rip + #20000` to actual value (if you're dealing with x86_64)?
e.g.)
`%9: $Unknown64(*?)  = #x20075e + rip`
 to 
`%9: $Unknown64(*?)  = #x60375e` (where 0xx60375e = #x20075e + rip) ?

**Comment by sushant94** [comment]
@kriw Yes, this is exactly the goal.
