### ISSUE TITLE
TODO in visual mode — unsupported arch?

### ISSUE THREAD

**Issue by resetnow** [radare/radeco-lib#38]
Hello,

I'm trying to use radeco (minidec) on xtensa elf binary (baremetal). After piping IR to minidec, most decompiled functions are empty (even when dead code elimination passes are disabled) and a few only contain CALL statements. Disassembly is visual mode is full of TODOs. Does this mean that this architecture is not supported by radeco or is this a problem with radare2 xtensa backend?

![screenshot from 2016-08-27 13-46-07](https://cloud.githubusercontent.com/assets/2057191/18026877/3fad5dba-6c65-11e6-9776-e964a3e07797.png)

**Comment by XVilka** [comment]
@resetnow this is because Xtensa doesn't fully support ESIL, which is needed as an input for radeco.

**Comment by resetnow** [comment]
@XVilka thanks!
