### ISSUE TITLE
Improvements to IR

### ISSUE THREAD

**Issue by sushant94** [radare/radeco-lib#49]
- [x] Store and display the original instruction (along with addresses)
- [x] Don't lose information related to register assignments. Store this information without breaking the SSA nature of the IR.
- [ ] Improve/Fix/Implement subtree printing, hashing and matching.

**Comment by XVilka** [comment]
- [ ] Handling custom ESIL ops - like a predefined function with comments, arguments and so on

**Comment by sushant94** [comment]
Closing this and opening separate issue for the remaining two tasks.
