### ISSUE TITLE
(Possible) Access to a replaced node leads to panic

### ISSUE THREAD

**Issue by l4l** [radare/radeco-lib#50]
After lurking through the code i guess i found out race condition(?) bug [here](https://github.com/radare/radeco-lib/blob/master/src/middle/phiplacement.rs#L355).

Here's the [patch](https://gist.github.com/l4l/dafebb40c526860590477f3345e4995c) to the master branch that i use for testing.
Here's the log example that hint to the bug:
![screenshot- - --2-22 51 30-msk-2017](https://cloud.githubusercontent.com/assets/5658339/21595597/0d321616-d149-11e6-8053-41e74e077f22.png)
As you can see there's missed Node 1826 after replacing it in other thread. And yeah i don't really sure that it's rc because each new launch still gives same output

**Comment by radare** [comment]
can you send a pr instead of posting a patch?

**Comment by l4l** [comment]
Why not, yeah
is [comparing against branch](https://github.com/radare/radeco-lib/compare/master...l4l:patch) fine? or you need a pr

**Comment by radare** [comment]
PR or GTFO

**Comment by l4l** [comment]
enjoy #51

**Comment by sushant94** [comment]
@l4l Why would there be a race condition, nothing inside radeco-lib is threaded.

Also, it seems to be that NodeIndex(1826) gets replaced by NodeIndex(1665), I mean, that's what's supposed to happen anyway.

**Comment by l4l** [comment]
Well, it was mostly a guess, i don't really know the code. Anyway it still has lots of panics at graph accessing (as well as failing test from time to time) so it can't be the intended behaviour 
And btw here's the spawn https://github.com/radare/radeco-lib/blob/master/src/frontend/containers.rs#L322 but meh, it doesn't lead to that place

**Comment by l4l** [comment]
Summary of last talk with @sushant94:
/bin/ls panics when adding replaced 38-th node (and only it).
Fails [here](https://github.com/radare/radeco-lib/blob/master/src/middle/ssa/ssastorage.rs#L618) and goes from [this call](https://github.com/radare/radeco-lib/blob/master/src/middle/phiplacement.rs#L361)
Type for NodeIndex(38) is NodeData::RegisterState

**Comment by P4N74** [comment]
Fixed by https://github.com/radare/radeco-lib/pull/62

**Comment by ZhangZhuoSJTU** [comment]
Closed for fixing.
