### ISSUE TITLE
GSoC Tasklist (dkreuter)

### ISSUE THREAD

**Issue by dkreuter** [radare/radeco-lib#7]
**Tasklist for GSoC-2015:**
- [x] Graph data structures, processing, API
- [x] Develop tests for graph infrastructure
- [ ] Implement pattern matching on the graph.
- [ ] Test pattern matching
- [x] Convert the parsed ESIL into SSA-ESIL.
- [x] Develop tests for SSA-ESIL.

----

- [ ] Variables propagation (*x = ?; *x → *x = t = ?; t)
- [ ] Tests for that.
- [x] Phi elimination.

**Comment by sushant94** [comment]
Closing this with updated checkboxes as GSoC is now over. @dkreuter feel free to open another issue when you need to.
