### ISSUE TITLE
RadecoProject as a container for RadecoModules 

### ISSUE THREAD

**Issue by chinmaydd** [radare/radeco-lib#72]
This issue will be used to discuss the design for `RadecoProject` and what goes inside it. 

Initial thoughts: (Most information lifted from r2, but setup during initialization)
```rust
pub struct RadecoProject<'a> {
    modules: HashMap<String, RadecoModule<'a, RadecoFunction>>, // <filename, instantiated module>
    arch: RArch, // possibly taken from arch-rs
    endian: Endian, // pub enum Endian { Big, Small }
}
```

Thoughts?

**Comment by sushant94** [comment]
PR #75 implements changes for this.
