### ISSUE TITLE
SubRegFile as a trait in radare2-r2pipe-api

### ISSUE THREAD

**Issue by chinmaydd** [radare/radeco-lib#88]
The logic in `regfile.rs` has the potential to be repeated in multiple projects. It would be nice to have a baseline `RegisterFile` trait which can then be extended as and when required. One example would be provide ValueTypes to the registers or have symbolic markers stored with them. 

This trait can be added to `radare2-r2pipe-api` and then extended here.

**Comment by sushant94** [comment]
I think this should be a part of arch-rs and reused in radare2-r2pipe-api to return results in the appropriate structs.

**Comment by ZhangZhuoSJTU** [comment]
Agree with `arch-rs`, it seems more logical, imho.

**Comment by chinmaydd** [comment]
Alright, makes sense.

**Comment by XVilka** [comment]
I agree on this too.

**Comment by chinmaydd** [comment]
Using the PR here for tracking purpose: https://github.com/radare/arch-rs/pull/1

**Comment by chinmaydd** [comment]
`RegisterFile` was implemented as a trait in `arch-rs` and a new issue(#114) was opened to generalize inclusion of various structures from the same, hence closing this.
